version: "3.0"

services:
  # FastAPI
  api:
    container_name: "api"
    command: "uvicorn main:backend --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ./backend:/backend:Z
    image: illumination27/biolab-database:latest
    restart: always
    tty: true
    ports:
      - 8001:8000

  db:
    image: postgres:11.7
    container_name: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main

  node:
    image: node:latest
    container_name: node_biolab
    volumes:
      - ./frontend:/mnt
    ports:
      - 3000:3000
    working_dir: /mnt
    command: "yarn dev"
    environment:
      - NEXT_PUBLIC_BACKEND_URL="http://api:8001"

# volumes:
#   postgres_data: {}
#   frontend: {}
