version: "3.0"

services:
  # FastAPI
  api:
    container_name: "api"
    command: "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
        - ./app:/app:Z
    build: .
    restart: always
    tty: true
    ports:
      - 8000:8000