version: "3.0"

services:
  # FastAPI
  api:
    container_name: "api"
    command: "uvicorn main:backend --reload --host 0.0.0.0 --port 8000"
    volumes:
        - ./backend:/backend:Z
    build: .
    restart: always
    tty: true
    ports:
      - 8000:8000
    
  db:
    image: postgres:11.7
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main